### PR TITLE
add specialization constant configuration

### PR DESCRIPTION
**Pull request by termhn**

### CODE REVIEW

**Comment by termhn** [comment]
Why did this not error for me on local build... lol.

**Comment by Frizi** [comment]
This time the fail is legit :(
```rs
error[E0507]: cannot move out of borrowed content
   --> shader/src/lib.rs:362:29
    |
362 |             specialization: self.specialization.unwrap_or(gfx_hal::pso::Specialization::default()),
    |                             ^^^^^^^^^^^^^^^^^^^ cannot move out of borrowed content
```

**Comment by termhn** [comment]
This is so weird, I've literally compiled and run with these changes working on my own machine... why is it failing on CI...

**Comment by omni-viral** [comment]
It should be `self.specialization.as_ref().unwrap_or(...)`

**Pull request merged**
