### PR TITLE
Add dyn RenderGroup API to subpass builder

### PR DESCRIPTION
**Pull request by Frizi**
This change allows explicitly passing boxed rendergroups to the pass. This doesn't add any cost, as concrete types were translated to boxes anyway.
This is required for easier implementation of ergonomic-friendly abstraction over rendergarph builder.

Additionaly fixed error reporting problems that I ran into when working on that.

### CODE REVIEW

**Comment by omni-viral** [comment]
bors retry

**Comment by Frizi** [comment]
bors retry

**Comment by omni-viral** [comment]
Apparently travis not going to build it today.

**Comment by omni-viral** [comment]
bors retry

**Comment by omni-viral** [comment]
Maybe today travis is not going to be nice.
bors retry

**Comment by omni-viral** [comment]
bors retry

**Pull request merged**
