### PR TITLE
Add window centering.

### PR DESCRIPTION
**Pull request by mralve**
Ahh after a long journey... finally this is the right repo, lol.

Added window centering functions such as center(), set_center_monitor(), set_centered() in wsi::WindowExt

this PR can be reverted if my PR (which provides the same functionality) on winit gets accepted.

### CODE REVIEW

**Comment by termhn** [comment]
Seems to me like this doesn't really belong in `rendy` but rather in `winit` itself since this functionality is rather orthogonal to rendering itself? `wsi` is basically just meant to provide minimum necessary interaction with windowing library in order to get it to integrate with gfx-hal/vulkan

**Comment by mralve** [comment]
@termhn No your right, I currently have a PR in Winit now, that is under review. so it will move there instead. wonder how it looks with winit in Rendy right now? winit got reverted to 0.18 some days ago, is there any major problems currently?

**Comment by torkleyy** [comment]
I think that revert was because gfx hasn't updated yet.

**Comment by Frizi** [comment]
We use winit 0.19 in `hal-master` branch, which gfx-hal master.

**Comment by Frizi** [comment]
winit has been updated alongside with hal 0.2 :)

**Pull request closed without merging**
