### PR TITLE
Add rasterizer parameter to Pipeline

### LINKED ISSUE #86: Support back-face culling in SimpleGraphicsPipeline
I believe this would only require configuration of the rasterizer field in the `GraphicsPipelineDesc` passed to `create_graphics_pipelines`.

https://github.com/omni-viral/rendy/blob/564e7e80824afc124d57c5220e57da20f12f8e8e/graph/src/node/render/group/simple.rs#L291

Edit: Also note that front-face culling is a good technique for avoiding shadow-acne while rendering shadow maps.

### PR DESCRIPTION
**Pull request by malte-v**
Adds a rasterizer parameter to `Pipeline` in order to support culling and conservative rasterization. Closes #86.

### CODE REVIEW

**Comment by omni-viral** [comment]
@malte-v Thank you!
Could you please fix conflict?

**Comment by malte-v** [comment]
Fixed!

**Comment by malte-v** [comment]
Fixed, for real now!

**Comment by omni-viral** [comment]
I've fixed conflict and merged it

**Pull request closed without merging**
